### ISSUE TITLE
count output files populated with 0

### ISSUE THREAD

**Issue by ghost** [sunthedeep/BarcodeCounter2#1]
After completing barcode counter analysis allbarcodecount.tab and mySamp_barcodeCounts.tab are populated with 0s. 

The barcodes are being correctly identified and counts are correct (check by hand for a small subset). 
Output files I have confidence in are:
mySamp_numReadsFoundPerSample.txt 
allSamplesConcatDedup.fasta
allSamplesConcatDedup.readCounts
mySamp_barcode.sam

Currently all of the bcs are being placed into the mySamp_numUnmappedReads.txt file. 

Can you please help me figure out why all of the reads are going to UnmappedReads file? Can you also confirm that if the barcodes are correctly sorted and not as unmapped reads that the allbarcodecounts and sample barcode counts would populate with counts for each identified barcode?

I'm using the same system as the Levy lab. Template and primer file used are identical to those found here.

I've attached my output files here and this is the command I ran:
python3 barcodeCounter_index_3.py -fastqDir 1bigbatch/rawFastqFiles/ -outputDir 1bigbatch/Lib17/ -templateSeq 1bigbatch/BC_template_011720.txt -sample 1bigbatch/Lib_sample_file.txt -multiBCFasta 1bigbatch/primerIndexSeq_L139_011720_2.fasta -pairedEnd -useUMI -numThreads 3 -DNAclustPATH ~/my_software/dnaclust_linux_release3/

[Lib17.zip](https://github.com/sandeepvenkataram/BarcodeCounter2/files/4783478/Lib17.zip)
 
Thanks in advance for helping me sort this issue out. Your time is much appreciated!

**Comment by sandeepvenkataram** [comment]
Hi! Sorry for the delayed response.

A summary of what I think is going on in these files:
The fastq files appear to be processed correctly. UMI sequences are identified, barcode sequences are extracted, and barcode clusters are generated i.e. "clusteredBCsDNAClust.fasta" is populated. Read mapping is attempted (sample_barcode.sam is generated), but mapping is not able to map sample_barcodes.fastq (which exists and is populated) to the clustered barcode fasta file.

I think the problem is with the bwa alignment parameters. they appear to be too strict, so the 20bp barcodes are being thrown out. Testing suggests that using bowtie2 instead with the default parameters does find matches, so I would try that. Alternatively, you can play with the bwa mapping parameters in line 739 of the current version of the code to try and get it to work with BWA. 

Please let me know if you have any further concerns, and thanks for using the software!
